name: intellij-ton snapshot

on:
  push:
    branches:
      - main
jobs:
  generate-build-number:
    runs-on: ubuntu-18.04
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        id: buildnumber
        with:
          token: ${{ secrets.github_token }}
          prefix: intellij-ton
  build:
    needs: [ generate-build-number ]
    runs-on: ubuntu-18.04
    env:
      ORG_GRADLE_PROJECT_buildNumber: ${{ needs.generate-build-number.outputs.build_number }}
      ORG_GRADLE_PROJECT_enableBuildSearchableOptions: true
      ORG_GRADLE_PROJECT_publishToken: ${{ secrets.plugin_bot_token }}
      ORG_GRADLE_PROJECT_publishChannel: snapshot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

#      - name: Publish intellij-ton plugin
#        uses: gradle/gradle-build-action@v1
#        with:
#          arguments: "publishPlugin"
